// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Kdo jsem",
  description: "Vr\xE1t\xED identitu aktu\xE1ln\u011B p\u0159ihl\xE1\u0161en\xE9ho u\u017Eivatele ZEdu (user_id, email).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nep\u0159ihl\xE1\u0161en\xFD u\u017Eivatel." }], isError: true };
    }
    const info = {
      user_id: ctx.getUserId(),
      email: ctx.getUserEmail() ?? null,
      client_id: ctx.getClientId() ?? null
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-my-classes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_classes_default = defineTool2({
  name: "list_my_classes",
  title: "Seznam m\xFDch t\u0159\xEDd",
  description: "Vr\xE1t\xED seznam t\u0159\xEDd, kter\xE9 p\u0159ihl\xE1\u0161en\xFD u\u010Ditel vlastn\xED, nebo (u studenta) t\u0159\xEDd, ve kter\xFDch je \u010Dlenem. Data se \u010Dtou pod RLS jako p\u0159ihl\xE1\u0161en\xFD u\u017Eivatel.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nep\u0159ihl\xE1\u0161en\xFD u\u017Eivatel." }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("classes").select("id, name, school, field_of_study, year, class_code, created_at").order("created_at", { ascending: false }).limit(100);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { classes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-assignments.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_assignments_default = defineTool3({
  name: "list_my_assignments",
  title: "Seznam m\xFDch \xFAloh",
  description: "Vr\xE1t\xED \xFAlohy (assignments) viditeln\xE9 p\u0159ihl\xE1\u0161en\xE9mu u\u017Eivateli pod RLS. Voliteln\u011B lze omezit po\u010Det.",
  inputSchema: {
    limit: z.number().int().optional().describe("Maxim\xE1ln\xED po\u010Det vr\xE1cen\xFDch \xFAloh (v\xFDchoz\xED 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Nep\u0159ihl\xE1\u0161en\xFD u\u017Eivatel." }], isError: true };
    }
    const n = Math.min(Math.max(Number.isFinite(limit) ? limit : 25, 1), 100);
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("assignments").select("id, title, description, due_at, created_at, class_id, status").order("created_at", { ascending: false }).limit(n);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { assignments: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rnndtpfmkanxbckdbflm";
var mcp_default = defineMcp({
  name: "zedu-mcp",
  title: "ZEdu",
  version: "0.1.0",
  instructions: "N\xE1stroje pro platformu ZEdu (u\u010Debnice, t\u0159\xEDdy, \xFAlohy). Volajte `whoami` pro ov\u011B\u0159en\xED identity, `list_my_classes` pro seznam t\u0159\xEDd p\u0159ihl\xE1\u0161en\xE9ho u\u017Eivatele a `list_my_assignments` pro jeho \xFAlohy. Data se \u010Dtou pod RLS jako p\u0159ihl\xE1\u0161en\xFD u\u017Eivatel.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_classes_default, list_my_assignments_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
