
INSERT INTO public.learning_methods (slug, name, description, category, difficulty, time_range, tips)
VALUES
  ('bloomova-taxonomie', 'Bloomova taxonomie', 'Hierarchie kognitivních cílů od zapamatování po tvořivost. Hodí se pro plánování otázek a úkolů, které postupně zvyšují náročnost myšlení.', 'kriticke_mysleni', 'stredni', '15–45 min', 'Formulujte úkoly slovesy odpovídajícími úrovni (pojmenuj → vysvětli → vytvoř).'),
  ('obracena-trida', 'Obrácená třída (Flipped classroom)', 'Studenti se seznámí s teorií doma (video/text) a ve třídě se procvičuje a diskutuje. Hodí se pro efektivní využití času v hodině.', 'aktivizacni', 'stredni', '45+ min', 'Předem připravte krátké video nebo text a ověřovací otázku.'),
  ('projektove-vyucovani', 'Projektové vyučování', 'Žáci pracují dlouhodobě na řešení reálného problému a vytvářejí konkrétní výstup. Hodí se pro mezipředmětové propojení a rozvoj kompetencí.', 'aktivizacni', 'pokrocila', '2+ hodiny', 'Definujte cíl, milníky a formu výstupu (prezentace, plakát, produkt).'),
  ('stanice-rotace', 'Stanice / rotace', 'Třída se rozdělí do skupin, které v časových blocích procházejí několik stanovišť s různými aktivitami. Hodí se pro střídání činností a diferenciaci.', 'kooperativni', 'stredni', '30–60 min', 'Připravte 3–5 stanic s jasnými instrukcemi a časovačem.'),
  ('kooperativni-uceni', 'Kooperativní učení', 'Skupinová práce, kde každý člen má jasnou roli a odpovídá za výsledek celku. Hodí se pro rozvoj spolupráce a komunikace.', 'kooperativni', 'stredni', '20–60 min', 'Přiřaďte role (mluvčí, zapisovatel, časoměřič) a hodnoťte i proces.'),
  ('gamifikace', 'Gamifikace', 'Prvky her (body, úrovně, žebříčky, odznaky) aplikované na běžné učení. Hodí se pro zvýšení motivace a zapojení.', 'aktivizacni', 'snadna', '15–45 min', 'Propojte body s konkrétními cíli, ne jen s docházkou.'),
  ('sokratovsky-dialog', 'Sokratovský dialog', 'Učitel klade cílené otázky, které vedou žáky k samostatnému odhalení pravidla nebo řešení. Hodí se pro rozvoj kritického myšlení.', 'kriticke_mysleni', 'pokrocila', '15–30 min', 'Připravte si posloupnost otázek; nekomentujte odpovědi hned.'),
  ('storytelling', 'Storytelling / narativní výuka', 'Učivo se předává formou příběhu s hrdinou, konfliktem a vývojem. Hodí se pro zapamatování a emocionální propojení s tématem.', 'prezentacni', 'snadna', '10–30 min', 'Postavte příběh na konkrétní postavě a jasné otázce.'),
  ('badatelska-vyuka', 'Badatelsky orientovaná výuka', 'Žáci si kladou otázky, formulují hypotézy, experimentují a vyhodnocují. Hodí se pro přírodovědné a společenskovědní téma.', 'aktivizacni', 'pokrocila', '45–90 min', 'Nechte žáky nejdřív navrhnout postup, ne mu jen předepsat.'),
  ('diferencovana-vyuka', 'Diferencovaná výuka', 'Úkoly, tempo a materiály jsou přizpůsobeny různým úrovním žáků. Hodí se pro heterogenní třídy a inkluzi.', 'reflexni', 'stredni', '30–60 min', 'Připravte 2–3 obtížnostní varianty téhož úkolu.')
ON CONFLICT (slug) DO NOTHING;
